services:
  web:
    build: .
    volumes:
      - .:/app
    volumes:
      - static_data:/app/static/

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # <-- We now listen on Port 80, not 8000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/static/  
    depends_on:
      - web  

volumes:
  static_data: