services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=taxproject.taxproject.settings
      - PYTHONPATH=/app/taxproject
    volumes:
      - .:/app
      - static_data:/app/taxproject/staticfiles/

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/taxproject/staticfiles/
    depends_on:
      - web

volumes:
  static_data: